[taxonomies]
vesselnames = "vesselname"


baseURL = "http://localhost:1313/"
title = "BargeHibernia"
theme = "blowfish"

[params.article]
showHero = true


[module]
[module.hugoVersion]
    extended = true
    min = "0.121.0"
    max = "0.147.5"


[[module.mounts]]
    source = "layouts"
    target = "layouts"

[[module.imports]]
    path = "github.com/natacast/blowfish"
