baseURL = 'https://burked9.github.io/bargehibernia/'
languageCode = 'en-us'
title = 'BargeHibernia'
theme = "blowfish"

[taxonomies]
vesselnames = "vesselname"

[params.article]
showHero = true

[module]
[module.hugoVersion]
    extended = true
    min = "0.121.0"
    max = "0.147.5"

[[module.mounts]]
    source = "layouts"
    target = "layouts"
